# Generated by Django 4.2.6 on 2023-10-19 21:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='png', keep_meta=True, null=True, quality=-1, scale=None, size=[512, 512], upload_to='photos/products'),
        ),
    ]
