# Generated by Django 4.2.6 on 2023-10-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='post_image',
        ),
    ]
