# Generated by Django 4.2.6 on 2023-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
    ]
