# Generated by Django 4.2.6 on 2023-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(default='Customer', max_length=20),
        ),
    ]
