# Generated by Django 4.2.6 on 2023-11-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Manager', 'Manager')], default='Customer', max_length=10),
        ),
    ]
