--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_account; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.accounts_account (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    phone_number character varying(50) NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    last_login timestamp with time zone NOT NULL,
    is_admin boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    is_superadmin boolean NOT NULL,
    role character varying(10) NOT NULL
);


ALTER TABLE public.accounts_account OWNER TO retailsdbuser;

--
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.accounts_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.accounts_userprofile (
    id integer NOT NULL,
    address_line_1 character varying(100) NOT NULL,
    address_line_2 character varying(100) NOT NULL,
    profile_picture character varying(100) NOT NULL,
    city character varying(20) NOT NULL,
    state character varying(20) NOT NULL,
    country character varying(20) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO retailsdbuser;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.accounts_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO retailsdbuser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO retailsdbuser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO retailsdbuser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cart; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.carts_cart (
    id integer NOT NULL,
    cart_id character varying(250) NOT NULL,
    date_added date NOT NULL
);


ALTER TABLE public.carts_cart OWNER TO retailsdbuser;

--
-- Name: carts_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.carts_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cartitem; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.carts_cartitem (
    id integer NOT NULL,
    quantity integer NOT NULL,
    is_active boolean NOT NULL,
    cart_id integer,
    product_id integer NOT NULL,
    user_id integer
);


ALTER TABLE public.carts_cartitem OWNER TO retailsdbuser;

--
-- Name: carts_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.carts_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cartitem_variations; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.carts_cartitem_variations (
    id integer NOT NULL,
    cartitem_id integer NOT NULL,
    variation_id integer NOT NULL
);


ALTER TABLE public.carts_cartitem_variations OWNER TO retailsdbuser;

--
-- Name: carts_cartitem_variations_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.carts_cartitem_variations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cartitem_variations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_category; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.category_category (
    id integer NOT NULL,
    category_name character varying(100) NOT NULL,
    slug character varying(200) NOT NULL,
    description text NOT NULL,
    cat_image character varying(100) NOT NULL
);


ALTER TABLE public.category_category OWNER TO retailsdbuser;

--
-- Name: category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.category_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO retailsdbuser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO retailsdbuser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO retailsdbuser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO retailsdbuser;

--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.orders_order (
    id integer NOT NULL,
    order_number character varying(20) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone character varying(15) NOT NULL,
    email character varying(50) NOT NULL,
    address_line_1 character varying(50) NOT NULL,
    address_line_2 character varying(50) NOT NULL,
    country character varying(50) NOT NULL,
    state character varying(50) NOT NULL,
    city character varying(50) NOT NULL,
    order_note character varying(100) NOT NULL,
    order_total double precision NOT NULL,
    tax double precision NOT NULL,
    status character varying(10) NOT NULL,
    ip character varying(20) NOT NULL,
    is_ordered boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    payment_id integer,
    user_id integer
);


ALTER TABLE public.orders_order OWNER TO retailsdbuser;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderproduct; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.orders_orderproduct (
    id integer NOT NULL,
    quantity integer NOT NULL,
    product_price double precision NOT NULL,
    ordered boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id integer NOT NULL,
    payment_id integer,
    product_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.orders_orderproduct OWNER TO retailsdbuser;

--
-- Name: orders_orderproduct_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.orders_orderproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderproduct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderproduct_variations; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.orders_orderproduct_variations (
    id integer NOT NULL,
    orderproduct_id integer NOT NULL,
    variation_id integer NOT NULL
);


ALTER TABLE public.orders_orderproduct_variations OWNER TO retailsdbuser;

--
-- Name: orders_orderproduct_variations_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.orders_orderproduct_variations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderproduct_variations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_payment; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.orders_payment (
    id integer NOT NULL,
    payment_id character varying(100) NOT NULL,
    payment_method character varying(100) NOT NULL,
    amount_paid character varying(100) NOT NULL,
    status character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.orders_payment OWNER TO retailsdbuser;

--
-- Name: orders_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.orders_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_generatedescription; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.store_generatedescription (
    id integer NOT NULL,
    description text NOT NULL,
    created_date timestamp with time zone NOT NULL,
    modified_date timestamp with time zone NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.store_generatedescription OWNER TO retailsdbuser;

--
-- Name: store_generatedescription_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.store_generatedescription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_generatedescription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_product; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.store_product (
    id integer NOT NULL,
    product_name character varying(200) NOT NULL,
    product_brand character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    description text NOT NULL,
    price integer NOT NULL,
    images character varying(100) NOT NULL,
    stock integer NOT NULL,
    is_available boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    modified_date timestamp with time zone NOT NULL,
    review_summary text NOT NULL,
    category_id integer NOT NULL
);


ALTER TABLE public.store_product OWNER TO retailsdbuser;

--
-- Name: store_product_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.store_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_productgallery; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.store_productgallery (
    id integer NOT NULL,
    image character varying(255) NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.store_productgallery OWNER TO retailsdbuser;

--
-- Name: store_productgallery_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.store_productgallery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_productgallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_reviewrating; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.store_reviewrating (
    id integer NOT NULL,
    subject character varying(100) NOT NULL,
    review text NOT NULL,
    rating double precision NOT NULL,
    ip character varying(20) NOT NULL,
    status boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    generated_response text NOT NULL,
    prompt text NOT NULL,
    product_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL
);


ALTER TABLE public.store_reviewrating OWNER TO retailsdbuser;

--
-- Name: store_reviewrating_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.store_reviewrating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_reviewrating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_variation; Type: TABLE; Schema: public; Owner: retailsdbuser
--

CREATE TABLE public.store_variation (
    id integer NOT NULL,
    variation_category character varying(100) NOT NULL,
    variation_value character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    created_date timestamp with time zone NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.store_variation OWNER TO retailsdbuser;

--
-- Name: store_variation_id_seq; Type: SEQUENCE; Schema: public; Owner: retailsdbuser
--

ALTER TABLE public.store_variation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_variation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_account accounts_account_email_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_email_key UNIQUE (email);


--
-- Name: accounts_account accounts_account_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_pkey PRIMARY KEY (id);


--
-- Name: accounts_account accounts_account_username_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_username_key UNIQUE (username);


--
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: carts_cart carts_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_pkey PRIMARY KEY (id);


--
-- Name: carts_cartitem carts_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_pkey PRIMARY KEY (id);


--
-- Name: carts_cartitem_variations carts_cartitem_variation_cartitem_id_variation_id_5f8efaf5_uniq; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem_variations
    ADD CONSTRAINT carts_cartitem_variation_cartitem_id_variation_id_5f8efaf5_uniq UNIQUE (cartitem_id, variation_id);


--
-- Name: carts_cartitem_variations carts_cartitem_variations_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem_variations
    ADD CONSTRAINT carts_cartitem_variations_pkey PRIMARY KEY (id);


--
-- Name: category_category category_category_category_name_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.category_category
    ADD CONSTRAINT category_category_category_name_key UNIQUE (category_name);


--
-- Name: category_category category_category_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.category_category
    ADD CONSTRAINT category_category_pkey PRIMARY KEY (id);


--
-- Name: category_category category_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.category_category
    ADD CONSTRAINT category_category_slug_key UNIQUE (slug);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderproduct orders_orderproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct
    ADD CONSTRAINT orders_orderproduct_pkey PRIMARY KEY (id);


--
-- Name: orders_orderproduct_variations orders_orderproduct_vari_orderproduct_id_variatio_8c028ee7_uniq; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct_variations
    ADD CONSTRAINT orders_orderproduct_vari_orderproduct_id_variatio_8c028ee7_uniq UNIQUE (orderproduct_id, variation_id);


--
-- Name: orders_orderproduct_variations orders_orderproduct_variations_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct_variations
    ADD CONSTRAINT orders_orderproduct_variations_pkey PRIMARY KEY (id);


--
-- Name: orders_payment orders_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_payment
    ADD CONSTRAINT orders_payment_pkey PRIMARY KEY (id);


--
-- Name: store_generatedescription store_generatedescription_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_generatedescription
    ADD CONSTRAINT store_generatedescription_pkey PRIMARY KEY (id);


--
-- Name: store_product store_product_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_product
    ADD CONSTRAINT store_product_pkey PRIMARY KEY (id);


--
-- Name: store_product store_product_product_name_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_product
    ADD CONSTRAINT store_product_product_name_key UNIQUE (product_name);


--
-- Name: store_product store_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_product
    ADD CONSTRAINT store_product_slug_key UNIQUE (slug);


--
-- Name: store_productgallery store_productgallery_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_productgallery
    ADD CONSTRAINT store_productgallery_pkey PRIMARY KEY (id);


--
-- Name: store_reviewrating store_reviewrating_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_reviewrating
    ADD CONSTRAINT store_reviewrating_pkey PRIMARY KEY (id);


--
-- Name: store_variation store_variation_pkey; Type: CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_variation
    ADD CONSTRAINT store_variation_pkey PRIMARY KEY (id);


--
-- Name: accounts_account_email_348850e2_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX accounts_account_email_348850e2_like ON public.accounts_account USING btree (email varchar_pattern_ops);


--
-- Name: accounts_account_username_b5f69a28_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX accounts_account_username_b5f69a28_like ON public.accounts_account USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: carts_cartitem_cart_id_9cb0a756; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX carts_cartitem_cart_id_9cb0a756 ON public.carts_cartitem USING btree (cart_id);


--
-- Name: carts_cartitem_product_id_acd010e4; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX carts_cartitem_product_id_acd010e4 ON public.carts_cartitem USING btree (product_id);


--
-- Name: carts_cartitem_user_id_4d21e0d9; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX carts_cartitem_user_id_4d21e0d9 ON public.carts_cartitem USING btree (user_id);


--
-- Name: carts_cartitem_variations_cartitem_id_8be23372; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX carts_cartitem_variations_cartitem_id_8be23372 ON public.carts_cartitem_variations USING btree (cartitem_id);


--
-- Name: carts_cartitem_variations_variation_id_ef9f9ee3; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX carts_cartitem_variations_variation_id_ef9f9ee3 ON public.carts_cartitem_variations USING btree (variation_id);


--
-- Name: category_category_category_name_1aa3ee61_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX category_category_category_name_1aa3ee61_like ON public.category_category USING btree (category_name varchar_pattern_ops);


--
-- Name: category_category_slug_4f83d5f6_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX category_category_slug_4f83d5f6_like ON public.category_category USING btree (slug varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: orders_order_payment_id_46928ccc; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_order_payment_id_46928ccc ON public.orders_order USING btree (payment_id);


--
-- Name: orders_order_user_id_e9b59eb1; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_order_user_id_e9b59eb1 ON public.orders_order USING btree (user_id);


--
-- Name: orders_orderproduct_order_id_5022a3e2; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_orderproduct_order_id_5022a3e2 ON public.orders_orderproduct USING btree (order_id);


--
-- Name: orders_orderproduct_payment_id_492ed997; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_orderproduct_payment_id_492ed997 ON public.orders_orderproduct USING btree (payment_id);


--
-- Name: orders_orderproduct_product_id_4d6ac024; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_orderproduct_product_id_4d6ac024 ON public.orders_orderproduct USING btree (product_id);


--
-- Name: orders_orderproduct_user_id_1e7a7ab7; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_orderproduct_user_id_1e7a7ab7 ON public.orders_orderproduct USING btree (user_id);


--
-- Name: orders_orderproduct_variations_orderproduct_id_0f116a3b; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_orderproduct_variations_orderproduct_id_0f116a3b ON public.orders_orderproduct_variations USING btree (orderproduct_id);


--
-- Name: orders_orderproduct_variations_variation_id_5dfd0e51; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_orderproduct_variations_variation_id_5dfd0e51 ON public.orders_orderproduct_variations USING btree (variation_id);


--
-- Name: orders_payment_user_id_cfa9f321; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX orders_payment_user_id_cfa9f321 ON public.orders_payment USING btree (user_id);


--
-- Name: store_generatedescription_product_id_2f3a617d; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX store_generatedescription_product_id_2f3a617d ON public.store_generatedescription USING btree (product_id);


--
-- Name: store_product_category_id_574bae65; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX store_product_category_id_574bae65 ON public.store_product USING btree (category_id);


--
-- Name: store_product_product_name_9d4b879d_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX store_product_product_name_9d4b879d_like ON public.store_product USING btree (product_name varchar_pattern_ops);


--
-- Name: store_product_slug_6de8ee4b_like; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX store_product_slug_6de8ee4b_like ON public.store_product USING btree (slug varchar_pattern_ops);


--
-- Name: store_productgallery_product_id_f2821a49; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX store_productgallery_product_id_f2821a49 ON public.store_productgallery USING btree (product_id);


--
-- Name: store_reviewrating_product_id_2e1974d6; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX store_reviewrating_product_id_2e1974d6 ON public.store_reviewrating USING btree (product_id);


--
-- Name: store_variation_product_id_e4f08cbc; Type: INDEX; Schema: public; Owner: retailsdbuser
--

CREATE INDEX store_variation_product_id_e4f08cbc ON public.store_variation USING btree (product_id);


--
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_accounts_account_id FOREIGN KEY (user_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id FOREIGN KEY (cart_id) REFERENCES public.carts_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_product_id_acd010e4_fk_store_product_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_product_id_acd010e4_fk_store_product_id FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_user_id_4d21e0d9_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_user_id_4d21e0d9_fk_accounts_account_id FOREIGN KEY (user_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem_variations carts_cartitem_varia_cartitem_id_8be23372_fk_carts_car; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem_variations
    ADD CONSTRAINT carts_cartitem_varia_cartitem_id_8be23372_fk_carts_car FOREIGN KEY (cartitem_id) REFERENCES public.carts_cartitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem_variations carts_cartitem_varia_variation_id_ef9f9ee3_fk_store_var; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.carts_cartitem_variations
    ADD CONSTRAINT carts_cartitem_varia_variation_id_ef9f9ee3_fk_store_var FOREIGN KEY (variation_id) REFERENCES public.store_variation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_account_id FOREIGN KEY (user_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_payment_id_46928ccc_fk_orders_payment_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_payment_id_46928ccc_fk_orders_payment_id FOREIGN KEY (payment_id) REFERENCES public.orders_payment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_user_id_e9b59eb1_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_user_id_e9b59eb1_fk_accounts_account_id FOREIGN KEY (user_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderproduct_variations orders_orderproduct__orderproduct_id_0f116a3b_fk_orders_or; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct_variations
    ADD CONSTRAINT orders_orderproduct__orderproduct_id_0f116a3b_fk_orders_or FOREIGN KEY (orderproduct_id) REFERENCES public.orders_orderproduct(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderproduct_variations orders_orderproduct__variation_id_5dfd0e51_fk_store_var; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct_variations
    ADD CONSTRAINT orders_orderproduct__variation_id_5dfd0e51_fk_store_var FOREIGN KEY (variation_id) REFERENCES public.store_variation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderproduct orders_orderproduct_order_id_5022a3e2_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct
    ADD CONSTRAINT orders_orderproduct_order_id_5022a3e2_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderproduct orders_orderproduct_payment_id_492ed997_fk_orders_payment_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct
    ADD CONSTRAINT orders_orderproduct_payment_id_492ed997_fk_orders_payment_id FOREIGN KEY (payment_id) REFERENCES public.orders_payment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderproduct orders_orderproduct_product_id_4d6ac024_fk_store_product_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct
    ADD CONSTRAINT orders_orderproduct_product_id_4d6ac024_fk_store_product_id FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderproduct orders_orderproduct_user_id_1e7a7ab7_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_orderproduct
    ADD CONSTRAINT orders_orderproduct_user_id_1e7a7ab7_fk_accounts_account_id FOREIGN KEY (user_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_payment orders_payment_user_id_cfa9f321_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.orders_payment
    ADD CONSTRAINT orders_payment_user_id_cfa9f321_fk_accounts_account_id FOREIGN KEY (user_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_generatedescription store_generatedescri_product_id_2f3a617d_fk_store_pro; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_generatedescription
    ADD CONSTRAINT store_generatedescri_product_id_2f3a617d_fk_store_pro FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_product store_product_category_id_574bae65_fk_category_category_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_product
    ADD CONSTRAINT store_product_category_id_574bae65_fk_category_category_id FOREIGN KEY (category_id) REFERENCES public.category_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_productgallery store_productgallery_product_id_f2821a49_fk_store_product_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_productgallery
    ADD CONSTRAINT store_productgallery_product_id_f2821a49_fk_store_product_id FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_reviewrating store_reviewrating_product_id_2e1974d6_fk_store_product_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_reviewrating
    ADD CONSTRAINT store_reviewrating_product_id_2e1974d6_fk_store_product_id FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: store_variation store_variation_product_id_e4f08cbc_fk_store_product_id; Type: FK CONSTRAINT; Schema: public; Owner: retailsdbuser
--

ALTER TABLE ONLY public.store_variation
    ADD CONSTRAINT store_variation_product_id_e4f08cbc_fk_store_product_id FOREIGN KEY (product_id) REFERENCES public.store_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

